### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [phoenix911/ProjectEuler_Android#1]
Hi guys, this a good app you have build. Are you considering adding it to the F-Droid store, this will be a "must have" for sure! :-)

**Comment by phoenix911** [comment]
I'm looking into it. v1.2.2 will also be uploaded in f-droid

**Comment by Poussinou** [comment]
Are you ok with the process or do you need some documentation about for exemple how to add your app to the F-Droid database?
